# Generated by Django 4.1 on 2022-09-05 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codintfunc', models.PositiveSmallIntegerField()),
                ('uf', models.CharField(max_length=2)),
                ('dt_admfunc', models.DateField()),
                ('dt_nascfunc', models.DateField()),
                ('nomefunc', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=200)),
                ('foto_perfil', models.ImageField(null=True, upload_to='images/')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_acesso', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
                ('post_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.posts')),
            ],
        ),
    ]
