# Generated by Django 4.1 on 2022-09-05 17:56

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='filial',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='non', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ramal',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[base.models.only_int]),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[base.models.check_tel]),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='non', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
